[development]
dynaconf_merge = true

[development.security]

# Token Secret Key
SECRET_KEY = "${SECRET_KEY}"

# API Parceiros Credentials
client_id = "${CLIENT_ID}"
client_secret = "${CLIENT_SECRET}"
