version: '3.9'

services:
  api:
    build:
      context: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      - TEST_APP=${TEST_APP}
    volumes:
      - .:/home/app/api
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true
  db:
    build: postgres
    restart: always
    volumes:
      - $HOME/.postgres/credito_db/data/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DBS=credito, credito_test
    env_file:
      - .env 
  redis:
    image: redis:7.0.11
    restart: always
    ports:
      - "6379:6379"
