"""initial

Revision ID: c57f3a013a52
Revises: 
Create Date: 2023-07-09 18:24:09.602369

"""
from alembic import op
import sqlalchemy as sa
#from alembic import op
#import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c57f3a013a52'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
